# This is a basic workflow to help you get started with Actions


name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  slack_bot_alert:
    runs-on: ubuntu-latest
    steps:
      - name: send alert to slackbot
        id: sendalert

        uses: tj-actions/changed-files@v23.1
     #   shell: bash
     #   run: |
      #    echo "::set-output name=enable-aws::true"
     #     echo "::set-output name=aws-cluster::cision"
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done